# Generated by Django 3.2.2 on 2021-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_alter_leave_form_remaining_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_leave_balance',
            name='leave_remaining',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
