# Generated by Django 3.2.2 on 2021-07-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0011_alter_my_leave_balance_leave_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_policy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leave_type',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='my_leave_balance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='my_leave_balance',
            name='leave_name',
        ),
        migrations.RemoveField(
            model_name='work_week_plan',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Leave_form',
        ),
        migrations.DeleteModel(
            name='Leave_policy',
        ),
        migrations.DeleteModel(
            name='Leave_type',
        ),
        migrations.DeleteModel(
            name='My_leave_balance',
        ),
        migrations.DeleteModel(
            name='Work_week_plan',
        ),
    ]
